# Generated by Django 4.2.4 on 2023-08-15 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_dish_options_alter_dishproduct_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='carbohydrates',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Углеводы'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='fats',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Жиры'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='proteins',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Белки'),
            preserve_default=False,
        ),
    ]
